from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
import time
d=webdriver.Chrome()
d.get("http://172.18.0.50:9003")
#time.sleep(10)
#me = By.XPATH, "//div[text()='我的']"
#d.find_element(me).click()
d.find_element_by_xpath("//div[text()='我的']").click()
d.find_element_by_xpath("//div[text()='点击登录']").click()
d.find_element_by_xpath("//input[@type='tel']").send_keys(13981401923)
d.find_element_by_xpath("//input[@type='password']").send_keys(123456)
d.find_element_by_css_selector(".shj-box-padding.flex-row.justify-content-center.shj-btn").click()
time.sleep(4)
d.find_element_by_xpath("//div[text()='订单']").click()
time.sleep(3)
#d.find_element_by_xpath("//span[@role='button' and @tabindex='0'and @aria-controls='dropdown-menu-7529']").click()
d.find_element_by_css_selector(".el-icon-caret-bottom.shj-color-footer").click()
time.sleep(3)
d.find_element_by_xpath("//li[text()='堂食订单']").click()
d.find_element_by_xpath("//div[text()='快捷午餐']").click()
time.sleep(5)
d.find_element_by_xpath("//div[text()='本地通测试店铺(商城)']").click()
time.sleep(8)
d.find_element_by_id("54392120").click()
time.sleep(2)
d.find_element_by_id("51432303").click()
time.sleep(4)
d.find_element_by_css_selector(".shj-height-38.submitSku").click()
time.sleep(2)
# d.find_element_by_xpath("/html/body/div/div/div[3]/div[2]/div").click()
#d.find_element_by_css_selector("div.shj-padding-15>div.shj-height-38.submitSku").click()
d.find_element_by_id("icon-cart").click()
time.sleep(3)
d.find_element_by_css_selector(".flex-row.align-items-center.shj-check-out").click()
time.sleep(3)
d.find_element_by_xpath("//span[text()='折扣码']").click()
time.sleep(3)
d.find_element_by_css_selector("div.el-input>input").send_keys(1234567890)#输入折扣码
time.sleep(4)
d.find_element_by_xpath("//div[text()='确定']").click()
time.sleep(3)
d.find_element_by_css_selector("div.el-input>input").send_keys(Keys.CONTROL,'a')
time.sleep(3)
d.find_element_by_css_selector("div.el-input>input").send_keys(Keys.BACK_SPACE,'123456')
time.sleep(4)
d.find_element_by_xpath("//div[text()='确定']").click()
time.sleep(3)
#d.find_element_by_xpath("/html/body/div/div/div[13]/div/div/i").click()
#d.find_element_by_xpath("//div[@class='flex-row'")
d.find_element_by_xpath("//div[@class='flex-row user-info']").click()
time.sleep(4)
d.find_element_by_xpath("//div[text()='haha']").click()
time.sleep(4)
d.find_element_by_xpath("//div[@class='shj-box-padding']").click()
time.sleep(4)
d.find_element_by_id("weui-picker-confirm").click()
time.sleep(4)
d.find_element_by_xpath("//div[@class='flex-row shj-foot-container']/div[2]").click()
#d.find_element_by_css_selector("flex-row.align-items-center.shj-bg-color-pink.shj-color-white.shj-submit-btn")